apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front-end
  labels:
    app: wfe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wfe
  template:
    metadata:
      labels:
        app: wfe
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
